version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/base_version:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nomnomnom
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nomnomnom_dev
