name: Build, Push and Deploy Elixir App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: arnewaeschenbach
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/arnewaeschenbach/nomnomnom:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Trigger Kubernetes deployment restart
      run: |
        ssh -o StrictHostKeyChecking=no root@49.13.157.152 "
          kubectl rollout restart deployment nomnomnom
        "
