name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Redeploy on Cluster
      run: |
        ssh -o StrictHostKeyChecking=no root@49.13.157.152 <<'EOF'
        kubectl rollout restart deployment/nomnomnom
        EOF
